package com.rknnovpn.panel.ipc

// Generated from daemon/internal/ipc/contract_manifest.json.
// Run .github/scripts/check_ipc_contract_codegen.py --write after editing the IPC contract.
internal object GeneratedDaemonContract {
    const val CONTRACT_VERSION: Int = 1
    val APK_REQUIRED_METHODS: Set<String> = setOf(
        "backend.applyDesiredState",
        "backend.reset",
        "backend.restart",
        "backend.start",
        "backend.status",
        "backend.stop",
        "diagnostics.health",
        "diagnostics.report",
        "diagnostics.testNodes",
        "ipc.contract",
        "logs",
        "profile.apply",
        "profile.get",
        "profile.importNodes",
        "profile.setActiveNode",
        "self-check",
        "subscription.preview",
        "subscription.refresh",
        "update-check",
        "update-download",
        "update-install",
        "version",
    )
    val METHOD_CAPABILITIES: Map<String, String> = mapOf(
        "app.list" to "privacy.audit.v2",
        "app.resolveUid" to "privacy.audit.v2",
        "audit" to "privacy.audit.v2",
        "backend.applyDesiredState" to "runtime.v2",
        "backend.reset" to "backend.reset.structured",
        "backend.restart" to "runtime.v2",
        "backend.start" to "runtime.v2",
        "backend.status" to "runtime.v2",
        "backend.stop" to "runtime.v2",
        "config-import" to "config.import.v2",
        "config-list" to "config.schema.v5",
        "diagnostics.health" to "diagnostics.health.v2",
        "diagnostics.report" to "diagnostics.bundle.v2",
        "diagnostics.testNodes" to "diagnostics.testNodes.v2",
        "ipc.contract" to "ipc.contract.v1",
        "logs" to "runtime.logs",
        "profile.apply" to "profile.apply.v2",
        "profile.get" to "profile.document.v2",
        "profile.importNodes" to "profile.importNodes.v2",
        "profile.setActiveNode" to "profile.apply.v2",
        "self-check" to "privacy.self-check.v1",
        "subscription.preview" to "profile.subscription.v2",
        "subscription.refresh" to "profile.subscription.v2",
        "update-check" to "update.install.v1",
        "update-download" to "update.install.v1",
        "update-install" to "update.install.v1",
        "version" to "ipc.contract.v1",
    )
    val MUTATING_METHODS: Set<String> = setOf(
        "backend.applyDesiredState",
        "backend.reset",
        "backend.restart",
        "backend.start",
        "backend.stop",
        "config-import",
        "profile.apply",
        "profile.importNodes",
        "profile.setActiveNode",
        "subscription.refresh",
        "update-download",
        "update-install",
    )
    val ASYNC_METHODS: Set<String> = setOf(
        "backend.reset",
        "backend.restart",
        "backend.start",
        "backend.stop",
        "config-import",
        "profile.apply",
        "profile.importNodes",
        "profile.setActiveNode",
        "subscription.refresh",
        "update-install",
    )
}
